jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.3.0'
  

# Process test results
  - bash: |
      curl https://gist.githubusercontent.com/n1k0/4332371/raw/14fdb095d43062da2a711e641b7b5e01ce455a32/log.xml -O
    displayName: 'Process test results'

# Publish test results to Azure Pipelines
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: 'log.xml' 
      failTaskOnFailedTests: true
    displayName: 'Publish tests'
