jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
      Python27:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python'
      Python37:
        python.version: '3.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python3'
      Markdown:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_MARKDOWN_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF'

  steps:
  - template: ci/linux-steps.yaml

- job: macOS
  pool:
    vmImage: macOS-10.13
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
      Python27:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF'
      Python37:
        python.version: '3.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF'

  steps:
  - template: ci/macos-steps.yaml

- job: WindowsVS14
  timeoutInMinutes: 360
  pool:
    vmImage: vs2015-win2012r2
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'

  steps:
  - template: ci/windows-vs14-steps.yaml

- job: WindowsVS15
  timeoutInMinutes: 360
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - template: ci/windows-vs15-steps.yaml

- job: WindowsVS16
  timeoutInMinutes: 360
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - template: ci/windows-vs16-steps.yaml