jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.3.0'
  - powershell: |
      nuget install boost -o $(Agent.ToolsDirectory) -Version 1.60.0
      nuget install boost_unit_test_framework-vc140 -o $(Agent.ToolsDirectory) -Version 1.60.0
      nuget install boost_program_options-vc140 -o $(Agent.ToolsDirectory) -Version 1.60.0
      nuget install boost_random-vc140 -o $(Agent.ToolsDirectory) -Version 1.60.0
      nuget install boost_serialization-vc140 -o $(Agent.ToolsDirectory) -Version 1.60.0
      nuget install boost_math_c99-vc140 -o $(Agent.ToolsDirectory) -Version 1.60.0
      nuget install OpenBLAS -o $(Agent.ToolsDirectory)

      mkdir boost_libs
      cp $(Agent.ToolsDirectory)\boost_program_options-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* boost_libs\
      cp $(Agent.ToolsDirectory)\boost_math_c99-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* boost_libs\
      cp $(Agent.ToolsDirectory)\boost_random-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* boost_libs\
      cp $(Agent.ToolsDirectory)\boost_serialization-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* boost_libs\
      cp $(Agent.ToolsDirectory)\boost_unit_test_framework-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* boost_libs\
      (New-Object Net.WebClient).DownloadFile("http://sourceforge.net/projects/arma/files/armadillo-7.800.2.tar.xz","armadillo.tar.xz")
      7z x armadillo.tar.xz -so | 7z x -si -ttar > nul
      cd armadillo-7.800.2
      mkdir build
      cd build
    displayName: 'Install Build Dependencies'
