jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.3.0'
  

# Process test results
  - bash: |
      curl https://gist.githubusercontent.com/zoq/39a6402b210800cf2ad2186a3e2466ad/raw/d4020a67dcfad0b95a750e5b8dde8e2fc81f413e/testxml.xml -O
    displayName: 'Process test results'

# Publish test results to Azure Pipelines
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: 'testxml.xml' 
      failTaskOnFailedTests: true
    displayName: 'Publish tests'
