jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.3.0'
  - powershell: |
      mkdir boost_libs
      (New-Object Net.WebClient).DownloadFile("http://masterblaster.mlpack.org:5005/armadillo-8.400.0.tar.gz","armadillo.tar.gz")
      tar -xvJ armadillo.tar.gz
    displayName: 'Install Build Dependencies'
