jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python'
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: |
      sudo apt-get update
      sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libarmadillo-dev xz-utils

      if [ "$python.version" = '2.7' ]; then
        sudo apt-get install -y --allow-unauthenticated python-pip cython python-numpy python-pandas
        sudo pip install --upgrade --ignore-installed setuptools cython
      fi

      # Install armadillo.
      curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-8.400.0.tar.xz | tar -xvJ && cd armadillo*
      cmake . && make && sudo make install && cd ..
      sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp
    displayName: 'Install Build Dependencies'
  - script: mkdir build && cd build && cmake $(CMakeArgs) ..
    displayName: 'CMake'
  - script: cd build && make -j4
    displayName: 'Build'
  - script: cd build && ctest -j4
    displayName: 'Run tests'
