jobs:


- job: WindowsVS15
  timeoutInMinutes: 360
  displayName: Windows VS17
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '3.6'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.3.0'
  
 # - task: DownloadPipelineArtifact@0
 #   inputs:
 #     artifactName: 'clcache.zip'
 #     targetPath: $(Agent.ToolsDirectory)\
 #   displayName: 'Fetch clcache'

#  - task: ExtractFiles@1
#    inputs:
#      archiveFilePatterns: 'clcache.zip'
#      destinationFolder: $(Agent.ToolsDirectory)\clcache
#      cleanDestinationFolder: true
#    displayName: 'Extract clcache'

# Pulling documentation and toolset for the installer
  - powershell: |
      pwd
      ls $(Agent.BuildDirectory)\s\
#ls d:\a\1\s\
      
      