trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- job: macOS
  timeoutInMinutes: 360
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      Python:
        binding: 'python'
        python.version: '3.8'
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'

  steps:
  - template: macos-steps.yaml
